"""Cost of the vanilla executor against the cost with the layer, in every environment.

For each executor X, the rows "X" and "X + SURVEYOR" (as in Table 1) give, at the longest goal distance of each environment,
the success rate, the wall-clock seconds per episode and the seconds per SOLVED episode (seconds per episode divided by the
success rate), which puts cost and benefit in one number. Everything comes from the harvested cells and the A100 scheduler
dumps through build_table1 (a row is timed by the arm whose success it prints). The lower seconds per solved episode of
each pair is bold. The table is refused while any cell is missing.

    python reproduce/build_costbenefit_table.py out/tables          # longest distance (tab:costbenefit)
    python reproduce/build_costbenefit_table.py out/tables short    # shortest distance
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import build_table1 as b          # noqa: E402
import build_table1_latex as L    # noqa: E402

OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "out", "tables")
SHORT = len(sys.argv) > 2 and sys.argv[2] == "short"


def num(v):
    return f"{v:.0f}" if v >= 100 else f"{v:.1f}"


def main():
    cells, cost = b.load_cells(), b.load_cost()
    t_of = {e: (b.T[e][0] if SHORT else b.T_COST[e]) for e in b.ENVS}
    lines = ["% generated by reproduce/build_costbenefit_table.py; do not edit by hand",
             "\\begin{tabular}{@{}l" + "rrr" * len(b.ENVS) + "@{}}", "\\toprule",
             "Executor & " + " & ".join(f"\\multicolumn{{3}}{{c}}{{{L.ENV_NAME[e]} $t{{=}}{t_of[e]}$}}" for e in b.ENVS) + " \\\\",
             "".join(f"\\cmidrule(lr){{{2 + 3 * i}-{4 + 3 * i}}}" for i in range(len(b.ENVS))),
             " & " + " & ".join("SR & s/ep & s/solved" for _ in b.ENVS) + " \\\\", "\\midrule"]
    missing = []
    for block, rows in L.block_iter(b.ROWS):
        x = L.X_NAME.get(block, block)
        pair = {}
        for key, spec, full, variant in rows:
            if variant or not (key.startswith("alone") or full):
                continue
            vals = {}
            for e in b.ENVS:
                c = b.cell(cells, e, spec.get(e), t_of[e])
                s = b.row_cost(cells, cost, e, spec.get(e), t_of[e])
                if c is None or s is None or c[1] < 8 or s[1] < 8:
                    missing.append((x, "full" if full else "vanilla", e, t_of[e]))
                    continue
                vals[e] = (c[0], s[0], s[0] / (c[0] / 100) if c[0] > 0 else float("inf"))
            pair["full" if full else "van"] = vals
        if missing:
            continue
        for kind, name in (("van", L.tex(x)), ("full", f"{L.tex(x)} + \\method{{}}")):
            out = []
            for e in b.ENVS:
                sr, sec, sol = pair[kind][e]
                other = pair["full" if kind == "van" else "van"][e][2]
                sol_txt = num(sol)
                if sol < other:
                    sol_txt = f"\\textbf{{{sol_txt}}}"
                out += [f"{sr:.1f}", f"{sec:.1f}", sol_txt]
            lines.append(f"{name} & " + " & ".join(out) + " \\\\")
        lines.append("\\midrule")
    if missing:
        print("NOT written, table_costbenefit" + ("_short" if SHORT else "") + ": missing or under-seeded " + str(missing[:6]))
        return
    lines[-1] = "\\bottomrule"
    lines.append("\\end{tabular}")
    fn = os.path.join(OUT, "table_costbenefit" + ("_short" if SHORT else "") + ("_gh200" if b.GH200 else "") + ".tex")
    with open(fn, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", fn)


if __name__ == "__main__":
    main()
