"""Appendix tables of the calibration and robustness batteries.

Everything is read from rb*_cells.csv through build_table1 (own-tolerance cells by default, the transferred cells with
OWN_PREFS switched off) and from the probe outputs in calibration/. Nothing is typed by hand except the one value that has
no file (Cube's block-only floor, 0.967; see calibration/README.md).

    python reproduce/build_robustness_tables.py [out_dir]

Writes: table_tolerances.tex   measured tolerance per environment, with its bootstrap interval
        table_transfer.tex     transferred (0.20 / 0.098) against own tolerance: mean success and call ratio
        table_tolsens.tex      full layer at the ends of each interval (battery X) and under other readings (Z, T2)
        table_dseeds.tex       drafter training seeds 42, 1, 2 (battery D, cells rbDS)
        table_kbudget.tex      drafting budget k (battery K2)
        table_oracle.tex       demonstration frames as subgoals (batteries Y and Y2)
A table with a missing or under-seeded cell is NOT written (the paper may not carry such a cell); the script says which.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
sys.path.insert(0, HERE)
import build_table1 as b  # noqa: E402

OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "out", "tables")
PROBES = os.path.join(ROOT, "calibration")
CUBE_BLOCK_ONLY = 0.967          # no probe output was kept; see calibration/README.md

EXECS = [("CEM (LeWM)", ""), ("GC-IDM", None), ("iCEM", "icem_"), ("MPPI", "mppi_"), ("Gradient (AdamW)", "gd_")]
ENV_NAME = {"pusht": "PushT", "reacher": "Reacher", "cube": "Cube", "tworoom": "Two-Room"}
TAU = {"pusht": "0.233", "reacher": "0.106", "cube": "0.794", "tworoom": "0.127"}
SERVED = {"pusht": "0.20", "reacher": "0.20", "cube": "0.20", "tworoom": "0.098"}
HEAD = "% generated by reproduce/build_robustness_tables.py; do not edit by hand"


class Incomplete(Exception):
    pass


def full_arm(pre):
    return "gcrouter_off_s42" if pre is None else pre + "router"


def need(c, what):
    if c is None or c[1] < 8:
        raise Incomplete(f"{what}: " + ("missing" if c is None else f"{c[1]} seeds"))
    return c


# Battery TR replaces the Two-Room full rows in the main tables only. The tolerance tables compare one
# configuration across tolerances, and on Two-Room every one of their runs read the probe against the accept rule's
# DINOv2-space tolerance (the arbiter never acted), so they keep the served runs: TR is switched off here.
def own(cells, env, arm, t):
    keep, b.TR_ON = b.TR_ON, False
    try:
        return need(b.cell(cells, env, arm, t), f"own {env} {arm} t={t}")
    finally:
        b.TR_ON = keep


def served(cells, env, arm, t):
    keep, b.OWN_PREFS, keep_tr, b.TR_ON = b.OWN_PREFS, [], b.TR_ON, False
    try:
        return need(b.cell(cells, env, arm, t), f"served {env} {arm} t={t}")
    finally:
        b.OWN_PREFS, b.TR_ON = keep, keep_tr


def raw(cells, pref, env, arm, t):
    return need(cells.get((pref, env, arm, t)), f"{pref} {env} {arm} t={t}")


def sr(c):
    return f"{c[0]:.1f}"


def sr_cr(c):
    return f"{c[0]:.1f}\\,{{\\scriptsize({c[2]:.2f})}}"


def write(name, lines):
    fn = os.path.join(OUT, name)
    with open(fn, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join([HEAD] + lines) + "\n")
    print("wrote", name)


# ---------------------------------------------------------------------------------------------------------------
def table_tolerances():
    def probe(fn, key):
        e = json.load(open(os.path.join(PROBES, fn)))[key]
        return e
    rows = [("PushT", "agent, block within $20$\\,px; angle within $20^\\circ$", probe("floor_pusht_U.json", "criterion_floor_20deg"), "0.20"),
            ("Reacher", "both joints within $0.05$\\,rad", probe("floor_reacher_U.json", "criterion_floor_reacher"), "0.20"),
            ("Cube", "block and effector within $0.04$\\,m", probe("floor_cube_U.json", "criterion_floor_cube"), "0.20"),
            ("Two-Room", "agent and target within $16$\\,px (DINOv2)", probe("gap_tworoom_paired_Z_fullscene.json", "equiv_criterion"), "0.098"),
            # battery TR: the same pairs in LeWM space, the tolerance of the Two-Room arbiter's probe
            ("", "the same pairs, LeWM (arbiter)", probe("gap_tworoom_lewm_TR_fullscene.json", "equiv_criterion"), None)]
    L = ["\\begin{tabular}{@{}llrrrrl@{}}", "\\toprule",
         # short headers: the long ones ran 89 pt past \linewidth; the caption says the pairs come from different episodes
         "Environment & Equivalent pairs & pairs & $10\\%$ & median $=\\tau$ & $90\\%$ & $95\\%$ interval \\\\",
         "\\midrule"]
    for env, eq, e, _ in rows:
        lo, hi = e["p50_ci95"]
        L.append(f"{env} & {eq} & {e['n']} & {e['p10']:.3f} & \\textbf{{{e['p50']:.3f}}} & {e['p90']:.3f} & $[{lo:.3f},\\,{hi:.3f}]$ \\\\")
    L += ["\\bottomrule", "\\end{tabular}"]
    write("table_tolerances.tex", L)


def table_transfer(cells):
    L = ["\\begin{tabular}{@{}l" + "rr" * 4 + "@{}}", "\\toprule",
         "Executor & " + " & ".join(f"\\multicolumn{{2}}{{c}}{{{ENV_NAME[e]}}}" for e in b.ENVS) + " \\\\",
         "".join(f"\\cmidrule(lr){{{2 + 2 * i}-{3 + 2 * i}}}" for i in range(4)),
         " & " + " & ".join(f"$\\tau{{=}}{SERVED[e]}$ & $\\tau{{=}}{TAU[e]}$" for e in b.ENVS) + " \\\\", "\\midrule",
         "\\multicolumn{9}{@{}l}{\\textit{Full layer, mean success rate (\\%) over the goal distances}} \\\\"]
    for name, pre in EXECS:
        vals = []
        for e in b.ENVS:
            for fn in (served, own):
                cs = [fn(cells, e, full_arm(pre), t) for t in b.T[e]]
                vals.append(f"{sum(c[0] for c in cs) / len(cs):.1f}")
        L.append(f"{name} & " + " & ".join(vals) + " \\\\")
    L += ["\\midrule", "\\multicolumn{9}{@{}l}{\\textit{Full layer, call ratio at the longest goal distance}} \\\\"]
    for name, pre in EXECS:
        vals = []
        for e in b.ENVS:
            for fn in (served, own):
                vals.append(f"{fn(cells, e, full_arm(pre), b.T[e][-1])[2]:.2f}")
        L.append(f"{name} & " + " & ".join(vals) + " \\\\")
    L += ["\\bottomrule", "\\end{tabular}"]
    write("table_transfer.tex", L)


def table_tolsens(cells):
    """one small tabular per environment: success (call ratio) of the full layer against the tolerance"""
    spec = {"pusht": [("0.173", "rbZ", "$5^\\circ$ test"), ("0.207", "rbX", "lower end"), ("0.233", None, "measured"), ("0.268", "rbX", "upper end")],
            "reacher": [("0.102", "rbX", "lower end"), ("0.106", None, "measured"), ("0.111", "rbX", "upper end")],
            "cube": [("0.759", "rbX", "lower end"), ("0.794", None, "measured"), ("0.826", "rbX", "upper end"), ("0.967", "rbZ", "block only")],
            "tworoom": [("0.098", "served", "same episode"), ("0.127", None, "measured"), ("0.142", "rbZ", "agent only")]}
    L = []
    for i, (env, cols) in enumerate(spec.items()):
        ts = (b.T[env][0], b.T[env][-1])
        L += ["\\begin{tabular}{@{}ll" + "r" * len(cols) + "@{}}", "\\toprule",
              f"{ENV_NAME[env]} & $t$ & " + " & ".join(f"$\\tau{{=}}{v}$" for v, _, _ in cols) + " \\\\",
              " & & " + " & ".join(f"{{\\scriptsize {lab}}}" for _, _, lab in cols) + " \\\\", "\\midrule"]
        for name, pre in EXECS:
            for j, t in enumerate(ts):
                vals = []
                for v, src, _ in cols:
                    arm = full_arm(pre)
                    if src is None:
                        c = own(cells, env, arm, t)
                    elif src == "served":
                        c = served(cells, env, arm, t)
                    else:
                        c = raw(cells, src, env, f"{arm}_tau{v}", t)
                    vals.append(sr_cr(c))
                L.append((f"\\multirow{{2}}{{*}}{{{name}}}" if j == 0 else "") + f" & {t} & " + " & ".join(vals) + " \\\\")
        L += ["\\bottomrule", "\\end{tabular}"]
        if i < len(spec) - 1:
            L.append("\\par\\vspace{6pt}")
    write("table_tolsens.tex", L)


def table_dseeds(cells):
    L = []
    for i, env in enumerate(("pusht", "reacher")):
        L += ["\\begin{tabular}{@{}ll" + "r" * len(b.T[env]) + "@{}}", "\\toprule",
              f"{ENV_NAME[env]} & drafter seed & " + " & ".join(f"$t{{=}}{t}$" for t in b.T[env]) + " \\\\", "\\midrule"]
        for k, (name, pre) in enumerate(EXECS):
            arm = full_arm(pre)
            for j, seed in enumerate(("42", "1", "2")):
                cs = [own(cells, env, arm, t) if seed == "42" else raw(cells, "rbDS", env, f"{arm}_ds{seed}_tauown", t)
                      for t in b.T[env]]
                lead = f"\\multirow{{3}}{{*}}{{{name}}}" if j == 0 else ""
                L.append(f"{lead} & {seed} & " + " & ".join(f"{c[0]:.1f}\\,{{\\scriptsize$\\pm${c[3]:.1f}}}" for c in cs) + " \\\\")
            L.append("\\midrule" if k < len(EXECS) - 1 else "\\bottomrule")
        L.append("\\end{tabular}")
        if i == 0:
            L.append("\\par\\vspace{6pt}")
    write("table_dseeds.tex", L)


def table_kbudget(cells):
    ks = {"pusht": (2, 3, 4, 8), "cube": (2, 3, 4, 8), "reacher": (2, 4, 8, 16)}
    L = []
    for i, env in enumerate(("pusht", "reacher", "cube")):
        L += ["\\begin{tabular}{@{}ll" + "r" * 4 + "@{}}", "\\toprule",
              f"{ENV_NAME[env]} & $t$ & " + " & ".join(f"$k{{=}}{k}$" for k in ks[env]) + " \\\\", "\\midrule"]
        for name, pre in EXECS:
            arm = full_arm(pre)
            k_served = (4 if pre is None else 8) if env == "reacher" else 3
            for j, t in enumerate((25, 150)):
                vals = []
                for k in ks[env]:
                    c = own(cells, env, arm, t) if k == k_served else raw(cells, "rbK2", env, f"{arm}_k{k}_tauown", t)
                    vals.append(sr_cr(c) + ("$^{\\ast}$" if k == k_served else ""))
                L.append((f"\\multirow{{2}}{{*}}{{{name}}}" if j == 0 else "") + f" & {t} & " + " & ".join(vals) + " \\\\")
        L += ["\\bottomrule", "\\end{tabular}"]
        if i < 2:
            L.append("\\par\\vspace{6pt}")
    write("table_kbudget.tex", L)


def table_oracle(cells):
    every = {"pusht": "ffjepa_s10k3", "reacher": "ffjepa_s10k8", "cube": "ffjepa_s10k3"}
    ts = (50, 100, 150)
    L = ["\\begin{tabular}{@{}ll" + "rrr" * 3 + "@{}}", "\\toprule",
         "Executor & Subgoals & " + " & ".join(f"\\multicolumn{{3}}{{c}}{{{ENV_NAME[e]}}}" for e in every) + " \\\\",
         "\\cmidrule(lr){3-5}\\cmidrule(lr){6-8}\\cmidrule(lr){9-11}",
         " & & " + " & ".join(f"$t{{=}}{t}$" for _ in every for t in ts) + " \\\\", "\\midrule"]
    search = [e for e in EXECS if e[1] is not None]
    for i, (name, pre) in enumerate(search):
        # short labels: nine numeric columns must fit \linewidth; the caption says that the last two rows serve demonstration frames
        rows = [("none (vanilla)", lambda e, t: own(cells, e, [pre + "flat_rh5", pre + "flat_rh2"], t)),
                ("drafter, every-step", lambda e, t: own(cells, e, pre + every[e], t)),
                ("demonstration, on schedule", lambda e, t: raw(cells, "rbY", e, pre + "oracle_s10", t)),
                ("demonstration, accept rule", lambda e, t: raw(cells, "rbY", e, pre + "voracle_s10", t))]
        for j, (lab, fn) in enumerate(rows):
            x = name.split(" (")[0]       # Table 1's short executor names (CEM, Gradient): the long ones overran \linewidth
            lead = f"\\multirow{{4}}{{*}}{{{x}}}" if j == 0 else ""
            L.append(f"{lead} & {lab} & " + " & ".join(sr(fn(e, t)) for e in every for t in ts) + " \\\\")
        L.append("\\midrule" if i < len(search) - 1 else "\\bottomrule")
    L.append("\\end{tabular}")
    write("table_oracle.tex", L)


def main():
    os.makedirs(OUT, exist_ok=True)
    cells = b.load_cells()
    for fn, args in ((table_tolerances, ()), (table_transfer, (cells,)), (table_tolsens, (cells,)), (table_dseeds, (cells,)),
                     (table_kbudget, (cells,)), (table_oracle, (cells,))):
        try:
            fn(*args)
        except Incomplete as e:
            print(f"NOT written, {fn.__name__}: {e}")


if __name__ == "__main__":
    main()
