"""Two main-text figures, generated as native pgfplots from the harvested cells (build_table1.load_cells / cell / row_cost).

fig_env_distance.tex   Figure 1, two rows in one figure environment:
                       (a) success against goal distance, one panel per environment, two lines per panel: the vanilla
                           executor (armNeutral) and the full layer (armOurs), each the mean over the four search executors.
                       (b) vanilla against the full layer at the two ends of the range: PushT and Reacher at the shortest
                           and the longest goal distance, horizontal bars per executor. One key for both rows.
fig_cost.tex           cost: wall-clock seconds per solved episode, vanilla (square) and full layer (circle) joined by a
                       rule, per executor, one panel per environment at its longest distance, one log axis for all panels
                       (A100 timings; the numbers are those of tab:costbenefit).

Every plotted number is a cell of the tables (or the mean of four cells, or the ratio of two table entries) and is written to
fig_main_data.csv with its source arms. Needs pgfplots (compat=1.16), groupplots, the tikz calc library, the preamble
colours armNeutral / armOurs and the \\method{} macro.

    python reproduce/build_fig_main.py [out_dir]       # default out/figures
"""
import csv
import os
import sys

import build_table1 as b
import build_table1_latex as bl

HERE = os.path.dirname(os.path.abspath(__file__))
FIG_DIR = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "out", "figures")
SEARCH = [("CEM (LeWM)", "CEM"), ("iCEM", "iCEM"), ("MPPI", "MPPI"), ("Gradient (AdamW)", "Gradient")]
GCIDM = ("GC-IDM (official code, s42)", "GC-IDM")
NAMES = ["CEM", "GC-IDM", "iCEM", "MPPI", "Gradient"]           # the tables' order
ENV_NAME = {"pusht": "PushT", "reacher": "Reacher", "cube": "Cube", "tworoom": "Two-Room"}
HEAD = "% generated by reproduce/build_fig_main.py from reproduce/rb*_cells.csv; do not edit by hand."
LEGEND = ("  legend columns=2, legend style={draw=black!25, font=\\footnotesize, inner ysep=1.5pt, nodes={inner ysep=1pt},\n"
          "                /tikz/every even column/.append style={column sep=0.9em}},")


def ladder():
    """display name -> {step: spec} for the five executors"""
    blocks = {name: rows for name, rows in bl.block_iter(b.ROWS)}
    out = {}
    for name, disp in SEARCH + [GCIDM]:
        if name not in blocks:
            name = next(k for k in blocks if k.startswith(name.split(" ")[0]))
        steps = {}
        for key, spec, full, variant in blocks[name]:
            if variant:
                continue
            if full:
                steps["full"] = spec
            elif key.startswith("alone"):
                steps["van"] = spec
        assert set(steps) == {"van", "full"}, (name, list(steps))
        out[disp] = steps
    return out


def f(x):
    return f"{x:.2f}"


def main():
    cells, cost = b.load_cells(), b.load_cost()
    lad = ladder()
    os.makedirs(FIG_DIR, exist_ok=True)
    data = []          # rows of the coordinate table

    def cell(disp, step, env, t, figure):
        c = b.cell(cells, env, lad[disp][step].get(env), t)
        if c is None or c[1] < 8:
            raise SystemExit(f"missing or under-seeded cell: {disp} {step} {env} t={t}")
        data.append({"figure": figure, "executor": disp, "step": step, "env": env, "t": t, "sr": f(c[0]), "se": f(c[3] or 0),
                     "value": "", "arm": str(lad[disp][step].get(env))})
        return c[0]

    # ---------------- figure 1, row (a): one panel per environment, two lines per panel ----------------
    # No key on this row: the colours are the figure's identity (armNeutral = vanilla, armOurs = the layer) and the one key
    # sits on row (b)'s axis-label row.
    L = [HEAD, "% Every coordinate is the mean of four cells (CEM, iCEM, MPPI, gradient); cells and source arms: figures/fig_main_data.csv.",
         "\\begin{figure}[t]", "\\centering", "\\begin{tikzpicture}", "\\begin{groupplot}[",
         "  group style={group size=4 by 1, horizontal sep=0.42cm, ylabels at=edge left, yticklabels at=edge left},",
         "  scale only axis, width=2.78cm, height=2.05cm,",
         "  ymin=0, ymax=100, enlarge y limits={upper, abs=4}, ytick={0,25,50,75,100},",
         "  ylabel={success (\\%)}, axis line style={black!40}, ymajorgrids, grid style={black!10},",
         "  tick label style={font=\\footnotesize}, label style={font=\\small}, title style={font=\\small, yshift=-3pt},",
         "  every axis plot/.append style={very thick, mark size=1.9pt},", "]"]
    for k, env in enumerate(b.ENVS):
        ts = b.T[env]
        opts = [f"title={{{ENV_NAME[env]}}}", f"xmin={ts[0]}", f"xmax={ts[-1]}", "enlarge x limits={abs=" + ("9" if ts[-1] > 75 else "4") + "}",
                "xtick={" + ",".join(str(t) for t in ts) + "}",
                # 75 stays a tick without a label where 100 follows it (the two labels would touch)
                "xticklabels={" + ",".join("{}" if (t == 75 and 100 in ts) else str(t) for t in ts) + "}"]
        if k == 1:
            opts += ["xlabel={goal distance $t$}", "xlabel style={xshift=1.6cm}"]
        L.append("\\nextgroupplot[" + ", ".join(opts) + "]")
        for step, colour, mark in (("van", "armNeutral", "square*"), ("full", "armOurs", "*")):
            mean = {t: sum(cell(d, step, env, t, "env-distance") for _, d in SEARCH) / len(SEARCH) for t in ts}
            L.append(f"% {ENV_NAME[env]}, {step}: mean over {', '.join(d for _, d in SEARCH)}")
            L.append(f"\\addplot[{colour}, solid, mark={mark}] coordinates {{" + " ".join(f"({t},{f(mean[t])})" for t in ts) + "};")
    L += ["\\end{groupplot}",
          "% row label, above the y-axis label column, clear of the first panel's title",
          "\\node[anchor=south west, inner sep=0pt, font=\\small\\bfseries] at ($(group c1r1.north west)+(-1.05cm,0.06cm)$) {(a)};",
          "\\end{tikzpicture}",
          "\\par\\vspace{1pt}"]

    # shared style of the two horizontal-bar figures: executors on the y axis, named once at the left
    BARS = ["  group style={group size=4 by 1, horizontal sep=0.42cm, yticklabels at=edge left},",
            "  scale only axis, width=2.62cm, height=1.75cm,",
            "  symbolic y coords={" + ",".join(NAMES) + "}, ytick=data, y dir=reverse, enlarge y limits=0.14,",
            "  axis line style={black!40}, xmajorgrids, grid style={black!10}, ytick style={draw=none},",
            "  tick label style={font=\\footnotesize}, label style={font=\\small}, title style={font=\\small, yshift=-3pt},"]

    # ---------------- figure 1, row (b): vanilla against the full layer at the two ends of the range ----------------
    L += ["\\begin{tikzpicture}", "\\begin{groupplot}["] + BARS + [
          "  xbar=0.6pt, /pgf/bar width=3.4pt, xmin=0, xmax=100, enlarge x limits={upper, abs=3}, xtick={0,50,100},",
          LEGEND, "  reverse legend, legend image code/.code={\\draw[#1] (0cm,-0.09cm) rectangle (0.22cm,0.13cm);},", "]"]
    k = 0
    for env in ("pusht", "reacher"):
        for t in (b.T[env][0], b.T[env][-1]):
            opts = ["title={" + ENV_NAME[env] + f", $t{{=}}{t}$" + "}"]
            if k == 0:
                opts.append("legend to name=leg:two-ends")
            if k == 1:
                opts += ["xlabel={success (\\%)}", "xlabel style={xshift=1.52cm}"]
            L.append("\\nextgroupplot[" + ", ".join(opts) + "]")
            # xbar stacks the first series lowest, so the full layer is plotted first and the legend is reversed:
            # vanilla reads above + SURVEYOR in every group, as in Table 1
            for step, style, label in (("full", "fill=armOurs, draw=armOurs!80!black", "+ \\method{}"),
                                       ("van", "fill=armNeutral!35, draw=armNeutral", "vanilla")):
                pts = " ".join(f"({f(cell(d, step, env, t, 'two-ends'))},{d})" for d in NAMES)
                L.append(f"\\addplot[{style}, line width=0.3pt] coordinates {{{pts}}};")
                if k == 0:
                    L.append(f"\\addlegendentry{{{label}}}")
            k += 1
    L += ["\\end{groupplot}",
          "% one key for both rows, on the axis-label row, right-aligned under the last panel (no extra height)",
          "\\node[anchor=east, inner sep=0pt] at ($(group c4r1.south east)+(0,-0.80cm)$) {\\ref{leg:two-ends}};",
          "% row label, above the executor-name column",
          "\\node[anchor=south west, inner sep=0pt, font=\\small\\bfseries] at ($(group c1r1.north west)+(-1.3cm,0.06cm)$) {(b)};",
          "\\end{tikzpicture}",
          # caption: bold title, the takeaway (headline figure only), what is plotted, where the full values are
          "\\caption{\\textbf{Success against goal distance, and at the two ends of the range.} \\textbf{(a)} Mean success of "
          "the four search executors: on PushT and Reacher \\method{} holds its success as the goal recedes while the vanilla "
          "executors fall; on Cube the gain is small, and on Two-Room it matches the vanilla executors at $t{=}25$ and gains beyond. "
          "\\textbf{(b)} Every executor at the two ends of PushT and Reacher. Means over eight repeated runs; \\Cref{app:full} gives "
          "every value.}",
          "\\label{fig:env-distance}", "\\end{figure}"]
    with open(os.path.join(FIG_DIR, "fig_env_distance.tex"), "w", newline="\n") as fh:
        fh.write("\n".join(L) + "\n")

    # ---------------- figure 3: cost per solved episode, full layer relative to vanilla ----------------
    # absolute seconds per solved episode. One row per executor: the vanilla value and the full layer's value, joined by a
    # rule, with Figure 1's markers and key; one log axis for all panels.
    C = [HEAD, "% x = (s/ep) / (SR/100): wall-clock seconds per solved episode, A100 timings (the values of tab:costbenefit).",
         "\\begin{figure}[t]", "\\centering", "\\begin{tikzpicture}", "\\begin{groupplot}["] + BARS + [
         "  xmode=log, xmin=0.4, xmax=1500, xtick={1,10,100,1000}, log ticks with fixed point, xminorticks=false,",
         "  /pgf/number format/1000 sep={}, ymajorgrids, every axis plot/.append style={mark size=1.9pt},", LEGEND, "]"]
    n_cheaper = 0
    for k, env in enumerate(b.ENVS):
        t = b.T_COST[env]
        opts = ["title={" + ENV_NAME[env] + f", $t{{=}}{t}$" + "}"]
        if k == 0:
            opts.append("legend to name=leg:cost")
        if k == 1:
            opts += ["xlabel={seconds per solved episode (log scale)}"]
        C.append("\\nextgroupplot[" + ", ".join(opts) + "]")
        per = {}
        for d in NAMES:
            for step in ("van", "full"):
                sr = cell(d, step, env, t, "cost")
                s = b.row_cost(cells, cost, env, lad[d][step].get(env), t)
                if s is None or s[1] < 8:
                    raise SystemExit(f"missing or under-seeded timing: {d} {step} {env} t={t}")
                per[d, step] = s[0] / (sr / 100.0)
                data[-1]["value"] = f"s/ep {s[0]:.3f}; s/solved {per[d, step]:.3f}"
            assert 0.4 < min(per[d, "van"], per[d, "full"]) and max(per[d, "van"], per[d, "full"]) < 1500, (env, d, per)
            n_cheaper += per[d, "full"] < per[d, "van"]
            # the rule becomes an arrow from vanilla to the layer where the change is large enough to show one (a factor above 3,
            # i.e. more than ~6 pt of rule between the markers); shorter rules stay plain under the markers
            big = max(per[d, "van"], per[d, "full"]) / min(per[d, "van"], per[d, "full"]) > 3.0
            style = "-{Latex[length=1.5mm, width=1.3mm]}, shorten >=1.0pt, " if big else ""
            C.append(f"\\addplot[{style}black!45, line width=0.9pt, mark=none, forget plot] coordinates {{({per[d, 'van']:.3f},{d}) ({per[d, 'full']:.3f},{d})}};")
        for step, colour, mark, label in (("van", "armNeutral", "square*", "vanilla"), ("full", "armOurs", "*", "+ \\method{}")):
            C.append(f"\\addplot[{colour}, only marks, mark={mark}] coordinates {{" + " ".join(f"({per[d, step]:.3f},{d})" for d in NAMES) + "};")
            if k == 0:
                C.append(f"\\addlegendentry{{{label}}}")
    C += ["\\end{groupplot}",
          "\\node[anchor=east, inner sep=0pt] at ($(group c4r1.south east)+(0,-0.80cm)$) {\\ref{leg:cost}};",
          "\\end{tikzpicture}",
          "\\caption{\\textbf{Cost per solved episode.} Wall-clock seconds per episode divided by the success rate, at the longest "
          "goal distance of each environment on one NVIDIA A100, means over eight repeated runs, with the vanilla executor timed "
          "at the lookahead whose success \\Cref{tab:main} prints. The layer is cheaper where the circle lies to the left of the "
          "square; \\Cref{app:cost} gives the values.}",
          "\\label{fig:cost}", "\\end{figure}"]
    with open(os.path.join(FIG_DIR, "fig_cost.tex"), "w", newline="\n") as fh:
        fh.write("\n".join(C) + "\n")

    with open(os.path.join(FIG_DIR, "fig_main_data.csv"), "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=["figure", "executor", "step", "env", "t", "sr", "se", "value", "arm"])
        w.writeheader()
        w.writerows(data)
    print(f"wrote fig_env_distance.tex, fig_cost.tex and fig_main_data.csv ({len(data)} cells); "
          f"cost: the layer is cheaper per solved episode in {n_cheaper} of 20 pairs")


if __name__ == "__main__":
    main()
