"""Appendix table `tab:competence` (batteries CB and CB2): the executor's search budget cut with everything else fixed.

Per level of the budget, the ten-step planner's success at t = 25 (vanilla) and success under every-step drafting at t = 150,
for CEM and iCEM on PushT and CEM on Reacher. Level 0 is the served budget and reads the cells the other tables print
(build_table1.get); the cut levels come from reproduce/rbCB_cells.csv and rbCB2_cells.csv. Nothing is typed by hand.

    python reproduce/build_competence_table.py out/tables
"""
import os
import sys

import build_table1 as b

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "out", "tables")
LEVELS = [(0, "300 \\times 30"), (1, "100 \\times 10"), (2, "30 \\times 5"), (3, "10 \\times 3"), (4, "10 \\times 1"),
          (5, "5 \\times 1"), (6, "2 \\times 1")]
GROUPS = [("PushT, CEM", "pusht", "flat_rh2", "ffjepa_s10k3"), ("PushT, iCEM", "pusht", "icem_flat_rh2", "icem_ffjepa_s10k3"),
          ("Reacher, CEM", "reacher", "flat_rh2", "ffjepa_s10k8")]


def main():
    cells = b.load_cells()
    lines = ["% generated by reproduce/build_competence_table.py; do not edit by hand",
             "\\begin{tabular}{@{}l" + "rr" * len(GROUPS) + "@{}}", "\\toprule",
             "Search budget & " + " & ".join(f"\\multicolumn{{2}}{{c}}{{{g[0]}}}" for g in GROUPS) + " \\\\",
             "".join(f"\\cmidrule(lr){{{2 + 2 * i}-{3 + 2 * i}}}" for i in range(len(GROUPS))),
             "samples $\\times$ iterations & " + " & ".join("$t{=}25$ & $t{=}150$" for _ in GROUPS) + " \\\\",
             "\\midrule"]
    missing = []
    for lvl, label in LEVELS:
        out = []
        for _, env, van, dr in GROUPS:
            for arm, t in ((van, 25), (dr, 150)):
                if lvl == 0:
                    c = b.get(cells, env, arm, t)
                else:
                    c = next((cells[(p, env, f"{arm}_cb{lvl}", t)] for p in ("rbCB", "rbCB2")
                              if (p, env, f"{arm}_cb{lvl}", t) in cells), None)
                if c is None or c[1] < 8 or c[3] is None:
                    missing.append((env, arm, lvl, t))
                    continue
                out.append(f"{c[0]:.1f}\\,{{\\scriptsize$\\pm${c[3]:.1f}}}")
        lines.append(f"${label}$" + (" (served)" if lvl == 0 else "") + " & " + " & ".join(out) + " \\\\")
    if missing:
        print("NOT written, table_competence: missing or under-seeded " + str(missing[:6]))
        return
    lines += ["\\bottomrule", "\\end{tabular}"]
    fn = os.path.join(OUT, "table_competence.tex")
    with open(fn, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote " + fn)


if __name__ == "__main__":
    main()
