"""Appendix table: success beyond t = 150 (batteries W and W2).

Reads rbW_cells.csv (and, for the t = 150 reference column, the same cells Table 1 uses through build_table1) and writes
table_beyond150.tex into the directory given as the first argument (default out/tables). Rows: the four search
executors, each alone (the better of the two horizons per cell, as in Table 1), every-step drafting, accept rule and
full layer. Columns: PushT at t = 150 / 175 / 200, Reacher and Cube at t = 150 / 175 / 195. Nothing is typed by hand:

    python reproduce/build_beyond_table.py [out_dir]
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import build_table1 as b  # noqa: E402

OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "out", "tables")
LONG = {"pusht": (175, 200), "reacher": (175, 195), "cube": (175, 195)}
EVERY = {"pusht": "ffjepa_s10k3", "reacher": "ffjepa_s10k8", "cube": "ffjepa_s10k3"}
EXECS = [("CEM (LeWM)", ""), ("iCEM", "icem_"), ("MPPI", "mppi_"), ("Gradient (AdamW)", "gd_")]
# short row labels: with the long ones the nine-cell table ran 37 pt past \linewidth
ROWS = [("vanilla", "alone"), ("every-step", "every"), ("accept rule", "accept"),
        ("\\textbf{full layer}", "full")]


def ref_cell(cells, env, pre, kind):
    """the t = 150 cell of Table 1's ladder (own tolerance where the row reads it)"""
    arm = {"alone": [pre + "flat_rh5", pre + "flat_rh2"], "every": pre + EVERY[env],
           "accept": pre + "surveyor", "full": pre + "router"}[kind]
    return b.cell(cells, env, arm, 150)


def long_cell(cells, env, pre, kind, t):
    names = {"alone": [pre + "flat_rh5", pre + "flat_rh2"], "every": [pre + EVERY[env]],
             "accept": [pre + "surveyor_tauown"], "full": [pre + "router_tauown"]}[kind]
    got = [cells.get(("rbW", env, a, t)) for a in names]
    if any(c is None or c[1] < 8 for c in got):
        raise SystemExit(f"missing or under-seeded cell: {env} {names} t={t}")
    return max(got, key=lambda c: c[0])


def fmt(c):
    return f"{c[0]:.1f}\\,{{\\scriptsize$\\pm${c[3]:.1f}}}"


def main():
    cells = b.load_cells()
    L = ["% generated by reproduce/build_beyond_table.py; do not edit by hand",
         "\\begin{tabular}{@{}ll" + "rrr" * 3 + "@{}}", "\\toprule",
         "Executor & Configuration & \\multicolumn{3}{c}{PushT} & \\multicolumn{3}{c}{Reacher} & \\multicolumn{3}{c}{Cube} \\\\",
         "\\cmidrule(lr){3-5}\\cmidrule(lr){6-8}\\cmidrule(lr){9-11}",
         " & & " + " & ".join(f"$t{{=}}{t}$" for env in LONG for t in (150,) + LONG[env]) + " \\\\",
         "\\midrule"]
    for i, (name, pre) in enumerate(EXECS):
        for j, (label, kind) in enumerate(ROWS):
            vals = []
            for env in LONG:
                vals.append(fmt(ref_cell(cells, env, pre, kind)))
                vals += [fmt(long_cell(cells, env, pre, kind, t)) for t in LONG[env]]
            lead = f"\\multirow{{{len(ROWS)}}}{{*}}{{{name}}}" if j == 0 else ""
            L.append(f"{lead} & {label} & " + " & ".join(vals) + " \\\\")
        L.append("\\midrule" if i < len(EXECS) - 1 else "\\bottomrule")
    L.append("\\end{tabular}")
    os.makedirs(OUT, exist_ok=True)
    fn = os.path.join(OUT, "table_beyond150.tex")
    with open(fn, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {os.path.abspath(fn)}: {len(EXECS) * len(ROWS)} rows x 9 cells")


if __name__ == "__main__":
    main()
